tasks:
  - init: pip install -r requirements.txt
    command: >
      PURPLE='\e[1;35m'; NOCOLOR='\e[0m';
      while [ -z "$XLWINGS_LICENSE_KEY" ]; do
        SET_LICENSE_KEY=1;
        printf "${PURPLE}Get your free trial license key at https://www.xlwings.org/trial\n${NOCOLOR}" &&
        read -p "Enter LICENSE_KEY: "  XLWINGS_LICENSE_KEY;
        APP_API_KEY=$(python -c "import secrets; print(secrets.token_hex(32))")
      done;
      if [ -z "$SET_LICENSE_KEY" ]; then
        :
      else
        gp env XLWINGS_LICENSE_KEY=$XLWINGS_LICENSE_KEY;
        gp env APP_API_KEY=$APP_API_KEY;
      fi;
      eval $(gp env -e);
      BASE_URL=$(gp url);
      URL=${BASE_URL/https:\/\//"https://8000-"}/hello;
      sed -i s@'"url"@'\""$URL"\"'@' ./js/xlwings_excel.ts;
      sed -i s@'"url"@'\""$URL"\"'@' ./js/xlwings_google.js;
      sed -i s@'"..."@'\""$APP_API_KEY"\"'@' ./js/xlwings_excel.ts;
      sed -i s@'"..."@'\""$APP_API_KEY"\"'@' ./js/xlwings_google.js;
      printf "${PURPLE}Your URL is: "${URL}" \n${NOCOLOR}";
      printf "${PURPLE}Your API_KEY is: "${APP_API_KEY}" \n${NOCOLOR}\n";
      python app/main.py
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
ports:
  - port: 8000
    onOpen: ignore
    visibility: public
