services:
  - type: web
    name: xlwings-remote-fastapi
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --chdir app --bind 0.0.0.0:8000 --access-logfile - --workers 2 --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: XLWINGS_API_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.3
      - key: XLWINGS_LICENSE_KEY
        sync: false
